name: Publish Testarchiver to Test Pypi
push:
    branches:
      - master
jobs:
    build-and-publish:
      name:  
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - name: Set up Python 3.8
          uses: actions/setup-python@v1
          with:
            python-version: 3.8
        - name: Install pep517
          run: >-
            python -m
            pip install
            pep517
            --user
        - name: Build a binary wheel and a source tarball
          run: >-
            python -m
            pep517.build
            --source
            --binary
            --out-dir dist/
        - name: Publish to Test PyPI
          uses: pypa/gh-action-pypi-publish@master
          with:
            password: ${{ secrets.test_pypi_api_token }}
            repository_url: https://test.pypi.org/legacy/
        
        - name: Publish distribution  to PyPI
            if: startsWith(github.event.ref, 'refs/tags')
            uses: pypa/gh-action-pypi-publish@master
            with:
              password: ${{ secrets.pypi_api_token }}
      